# Use an official Python runtime as a base image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV FLASK_APP=app.py

# Run the application
CMD ["flask", "run", "--host=0.0.0.0"]




# # Use an official Python runtime as the base image
# FROM python:3.11-slim

# # Set the working directory inside the container
# WORKDIR /app

# # Install Supervisor
# RUN apt-get update && apt-get install -y supervisor

# # Copy your entire application into the container
# COPY . /app

# # Install Python dependencies for both Flask and Dash apps
# RUN pip install -r /app/requirements.txt

# # Expose ports for Flask (5000) and Dash (8050)
# EXPOSE 5000 8050

# # Copy the Supervisor configuration file into the container
# COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# # Command to run Supervisor
# CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]


